implement active/inactive state restore
jenspfahl/KeepAwake pull request #11
Opened 2017-09-16 15:00 UTC by neffo

See #8 

Added a third setting for the indicator toggle which will restore the video mode after a shell or system restart. This is indicated by a small lock on the icon.

I've added an additional dconf key to store this. I've tried to minimise other code changes.

2017-10-17 18:17 UTC, cyberalex4life approved these changes

2017-10-18 20:49 UTC, cyberalex4life commented
@neffo and @jenspfahl , I think there's a misspelled variable on this commit:
"extension.js", line 402
`_mode = _MODE_ON_LOCK; `
should be
`_mode = MODE_ON_LOCK;`
I get _MODE_ON_LOCK  undefined variable.

2017-10-18 23:04 UTC, neffo commented
@cyberalex4life fixed!

2017-10-19 18:52 UTC, jenspfahl requested changes
Would be nice to shortly mention the new feature in README.md. Please see my other comments.

Btw, good work!

2017-10-19 18:52 UTC, jenspfahl commented on KeepAwake@jepfa.de/extension.js
> +
Please move both methods below getPowerBat(), so every property-getter/setter are side by side.

2017-10-19 18:52 UTC, jenspfahl commented on KeepAwake@jepfa.de/extension.js
> +        // on --> on with lock
Comment should be `// on with lock --> off`

2017-10-19 18:52 UTC, jenspfahl commented on KeepAwake@jepfa.de/extension.js
>          _tweenText = new St.Label({ style_class: 'video-label-on', text: _("Computer keeps awake.") });
I think it is better to show an additional message when toggling to MODE_ON_LOCK, e.g. "Computer keeps awake even after restart. "

2017-10-20 01:08 UTC, neffo commented
Sorry, not sure how to add the README.md file to this pull request, but other changes have been made as requested.

2017-10-22 14:50 UTC, jenspfahl approved these changes

2017-10-22 14:50 UTC, merged